### ISSUE TITLE
[Suggestion] When mouse over on expand column, parent row shouldn't display hover style.

### ISSUE THREAD

**Issue by ashleyyang0610** [trendmicro-frontend/react-table#13]
On style portal, it doesn't define expand column style.
For common user experience, when user mouse over expand column, its parent row shouldn't show hover style.

**Comment by js-pankaj-rana** [comment]
Facing the same issue, when I hover over the expanded row, the action.handleExpandedRowRender method is triggering every hover.

Link is below

https://github.com/trendmicro-frontend/react-table/blob/master/examples/tables/ExpandedRow.jsx

**Comment by tinaClin** [comment]
Fixed in v2.0.1
