### ISSUE TITLE
Fixed headers misaligned with columns in wide tables

### ISSUE THREAD

**Issue by cheton** [trendmicro-frontend/react-table#2]
This happened on Windows, not on Mac.

![image](https://cloud.githubusercontent.com/assets/447801/24396989/92532206-13d7-11e7-88b6-828457687c95.png)

**Comment by tinaClin** [comment]
Fix the issue that headers misaligned with columns in wide table. (a97c85162a94108eb8708357c55cdc977a69d46f)

http://stackoverflow.com/questions/4185814/fixed-table-cell-width

**Comment by cheton** [comment]
* Misaligned by 1px
![image](https://cloud.githubusercontent.com/assets/447801/24401802/6754abae-13e8-11e7-892e-d6562ff908aa.png)

* Misaligned when sorting
![image](https://cloud.githubusercontent.com/assets/447801/24401728/2201c4ce-13e8-11e7-8374-6b247aedac47.png)

**Comment by tinaClin** [comment]
Add empty column to the end of header, and set its width to scrollbar width for avoiding to misalign with columns during scrolling table. (7c1080bbed648890845045b33002e45fb5d72f63)
