### ISSUE TITLE
The table component will scroll to the top when scrolling the Textarea in the expending row content

### ISSUE THREAD

**Issue by sean1093** [trendmicro-frontend/react-table#30]
The table component will scroll to the top when scrolling the Textarea in the expending row content. 

## Development Env
* React version: 16.8.1 
* @trendmicro/react-table version: 1.0.1-alpha.2

## Issue Detail 
* When doing scroll action inside the Textarea in expanding row content
* It will trigger the table component scroll to the top immediately

![react-table-issue](https://user-images.githubusercontent.com/8320647/69947621-f9ad9800-1528-11ea-924b-bdbef40f513e.gif)

**Comment by tinaClin** [comment]
Hi @sean1093,
This issue is not reproduced in v2.0.0, so I close it.
